# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    http_manager:
        class: AppBundle\Manager\HttpManager
        calls:
            - [ setRequest, [ '@?request=' ] ]

    csvey_api.user_survey_manager:
        class: AppBundle\Manager\UserSurveyManager
        arguments:
            - '@doctrine'

    csvey_api.survey_manager:
        class: AppBundle\Manager\SurveyManager
        arguments:
            - @doctrine

    csvey_api.user_manager:
        class: AppBundle\Manager\UserManager
        arguments:
            - @doctrine

    twilio_calling_manager:
        class: AppBundle\Manager\TwilioCallingManager
        arguments:
            - %twilio_ssid%
            - %twilio_secret%
            - %twilio_verified_number%

    twilio_message_manager:
        class: AppBundle\Manager\TwilioMessageManager

    csvey_api.health_tip_manager:
      class: AppBundle\Manager\HealthtipManager
      arguments:
        - @doctrine

    twilio_message_handling_manager:
        class: AppBundle\Manager\TwilioMessageHandlingManager
        arguments:
            - '@csvey_api.survey_manager'
            - '@csvey_api.user_manager'
            - '@csvey_api.health_tip_manager'
