# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    http_manager:
        class: AppBundle\Manager\HttpManager
        calls:
            - [ setRequest, [ '@?request=' ] ]

    user_survey_manager:
        class: AppBundle\Manager\UserSurveyManager
        arguments:
            - '@doctrine'

    twilio_calling_manager:
        class: AppBundle\Manager\TwilioCallingManager
        arguments:
            - %twilio_ssid%
            - %twilio_secret%
            - %twilio_verified_number%
